language: cpp
compiler: gcc
dist: xenial
sudo: false

before_install:
  - uname -a
  - sudo apt-get update -qq
  - g++ --version
  - python3 --version
  - cmake --version
  - git clone https://github.com/Mogball/opencv3-debian.git
  - sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libv4l-dev liblapacke-dev libgtk-3-dev libopenblas-dev libhdf5-dev libtesseract-dev libleptonica-dev gfortran -y -qq
  - sudo apt-get install ffmpeg -y -qq
  - sudo dpkg -i opencv3-debian/opencv3_3.4.0-1_amd64.deb

install:
  - sudo apt-get install qt5-default qtmultimedia5-dev -y -qq
  - sudo apt-get install libfontconfig1 mesa-common-dev libglu1-mesa-dev libudev-dev libxi6 libsm6 libxrender1 libegl1-mesa libxine2 -y -qq

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  slack: uwnrg:zSxSzV4CSAa1o8tA6jjMCJSP
